[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "bfc5dd76ef0fcf5b4190b11c714e8575adef4eb6"
os = "macos"

    [[HiGHS.download]]
    sha256 = "85afddfd0032e23a6c757ea829e18ac53bbced59edf5f68d83e8d1494a564919"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.aarch64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4a7c36107246808b2dc450ec5e983ce452870ca"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "c5488e12f4b3699907cb449126eba064c5e56a10b41e54b2a0d409fd52314b16"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "177613a73bcf7514013fb50c6e5b951f617194b9"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "2de386a8bd13c20500edae0f51379d0d980cd5e3d5382173e2f2ac0d9e2e2e04"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "e000d1addc80d9406562d33d23a83f68f0306b33"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "fb1f3a58af7c9aabdbb4e47c8d8a71f2cac8bb1978f3dbf6738ec3318689aaa4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.aarch64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a0258fad45975dd4f174dd89d816ce39f878fe3"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "0f5570bf7d6e0bf1cf0ec9d0fd5f5d3acd49ec05b84174d60abc525ae31b8a2e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "064feeee405807ffb4e6033d4da8d39f48d7b53f"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "b8881956c08ef8454c233f585a1d294c6de6f6841ea56d23642e656f94abac4d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f6575093bb951d2d5a1f9946b4a5f6ae2ee72e1"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "73f69bb01486fb68164e23eb5752761fbb85a5654d124407679628a805a29a4b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4a33a5527e6ba9ee268db78bb9e0a1553167f58"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "18de130061d99d1d32b4a6aac4a6c5b064857f4c0a56234964dcaf54fa0ec8a5"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599bbfbf9ca7f67a75c299331047cc51d7f06acf"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "08bd7617689937ee10accf9b866ec4f0ae695bba60bee0b0e632ae8518309da8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.i686-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b572f09c90ef363b11511fbed6c6590848154fe"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "eb18a7089e1fd876d009ddb73bdfe12adb8ccf2ff0a42808e5afc39ed6b4b21a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.i686-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aa94fc1a51946aec57c7415de62c50742659e2f"
os = "windows"

    [[HiGHS.download]]
    sha256 = "a35a4883e799d6478c3aa2b74f130df905aa5bde3a01d4f937e5c196fa162685"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.i686-w64-mingw32-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "81ff8faf25a41964b08b82bf9f983483580a5988"
os = "macos"

    [[HiGHS.download]]
    sha256 = "a22e19eae81b348b1b6e23ad3c315843e62dd8f33f158bf3b7f4d7b089e4a71a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.x86_64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57846bf52e8d91e2d6dfef3b0e474315208dc524"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "3bf8ba4b53be90f8a36d6ad12fdb09ab6ebe572aaa3ea405509daf7c2e10d7fb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c449c7b2e6eddb7cec1fe664ed4f3067555c612d"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "398bafc6dee3369196bb3a42f0859661da4382300f045ee80fecba39d1d8119a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "e0e4f9d5625d4f4d361eb50dc95df7402eded809"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "40bb13efb8783b2387058d68f13428f6d901f0159472876ca03d7c80b8ce6cb2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.x86_64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "850e1dc05307e8426ae5684d0138d75824edb262"
os = "windows"

    [[HiGHS.download]]
    sha256 = "5c2b5d7d0caa8b22124c640f982819bc636e0eb2542e718a821260e143ee868f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.1+0/HiGHS.v1.13.1.x86_64-w64-mingw32-cxx11.tar.gz"
