[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "f5f7c2931d45251d41743d5238da3899265fd771"
os = "macos"

    [[HiGHS.download]]
    sha256 = "b80aa5af72d0ece03c39961ae6a5ddc144c42731f56aa7d6d9e8386e3e5538d0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.aarch64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ca72b2d84bb42813fb449d98e8d0bc1cf9e7ab8"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "5049d1c0377ba7719a7420a81d95ba6f2499803ba01d638dc398a47b7fbc3f34"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32665bcb6b4c6c06fb2f716572a187fcf5a75dc5"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "fcb402fdfe4f09a1cd08133bde67a0aec82bd9778823a2b50539761cc13d873c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "aarch64"
git-tree-sha1 = "e7b0adedd4f90096489b89d8cbdf661d50b759e4"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "dd0317d0f573d01a87dbb9abe22efcd72139a0fff691ca4a95615601283f66a3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.aarch64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d334a8b8bc040aa9c9eb3f01a77a78d9ecd35c2"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "33c6019013249214e2a0ef69d333e512341bf4fe5283fd98e8d6de77bbe0c493"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5310a534cfde5934fc7d437ef08b7daea7348cdc"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "e01b136316d4328817798f8a90587936ad23152b9de38eceeb6b764d6f5d3694"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a7126037e81ce3a64d3ec9c93217f68ff314b56"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "66e763ce86a786bc3289366b75ea4d0236fef67931a0533ac2135e5e87dc5db4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bf1d9f9945ea9affc8226bf9bb5af7546a0340e"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "8cfed06714113c4f980b52eff64b0c6976756d564f8fbf1ba16d315b13fe8c98"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82213c71fc9cd8baa82ec4050d3e457a70023fc2"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "0527f07894b0fbff3a19f2202728946bf5917ceb744c7eae341ee59bbd77d57c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b2a98435674f8d7f9bc2cc62c4c7fd1ad45c0cb"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "5b072f707c3046e0cdca8bbecaa76f2c3911545ccf8df558bf310194e16efe65"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b41ef3af9d2d0bb91b19d895c79a5a544f62d25"
os = "windows"

    [[HiGHS.download]]
    sha256 = "29c0d474aeb6e92db4a80373f71a609941850770b008d6c12b2a2592f9c9a39b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.i686-w64-mingw32-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "2d0292fd49c2b3def56da35b72a5db6321eb111a"
os = "macos"

    [[HiGHS.download]]
    sha256 = "8d1362dd2f8c1becf1a59c54470ddf82daf0c327789794199107407ca0274db7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.x86_64-apple-darwin.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "634f5b203e1b48dd0c38b141e6b690f494632d7c"
libc = "glibc"
os = "linux"

    [[HiGHS.download]]
    sha256 = "a46f7b4703d1368458f2b2b279bff1b9477e708c18c79c4f644444dcaba59f5a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7de210ef15a2f75b22e26311fd08cf38941eac8"
libc = "musl"
os = "linux"

    [[HiGHS.download]]
    sha256 = "afab28ad7d7ce4fc8abc0070bad5d3b25f68fac077f481496aec28e7eff6fa80"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHS]]
arch = "x86_64"
git-tree-sha1 = "50f42b1894f46c86a9f10bdb5db03e3e5c888330"
os = "freebsd"

    [[HiGHS.download]]
    sha256 = "2cbc35e1260a323a01ec3bb29e2520ac8f4c613cdf932f9306cd363144516fb4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34ce9afd60d67b66632b00fbefbdd3d856ea30d0"
os = "windows"

    [[HiGHS.download]]
    sha256 = "7a00e93bf7783fc67b4807a52240fff53a72b1a7000e59883170e57e7318e374"
    url = "https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.13.0+0/HiGHS.v1.13.0.x86_64-w64-mingw32-cxx11.tar.gz"
